# Generated by Django 5.2.6 on 2025-09-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('holiday_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(choices=[('lbs', 'lbs'), ('balls', 'balls'), ('cans', 'cans'), ('units', 'units')], default='units', max_length=16)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reorder_level', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSales',
            fields=[
                ('order_details_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('pizza_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('pizza_size', models.CharField(max_length=5)),
                ('pizza_category', models.CharField(max_length=255)),
                ('pizza_ingredients', models.TextField()),
                ('pizza_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('datetime', models.DateField(primary_key=True, serialize=False)),
                ('tempmax', models.FloatField()),
                ('tempmin', models.FloatField()),
                ('temp', models.FloatField()),
                ('precip', models.FloatField()),
                ('snow', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('sealevelpressure', models.FloatField()),
                ('cloudcover', models.FloatField()),
                ('visibility', models.FloatField()),
                ('uvindex', models.FloatField(blank=True, null=True)),
                ('conditions', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('current_stock', models.FloatField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='predictor.ingredient')),
            ],
            options={
                'unique_together': {('date', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='predictor.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='predictor.pizzarecipe')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
